<!DOCTYPE html>
<html lang="zh-cn">
<head prefix="og: http://ogp.me/ns#">
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
  <meta property="og:title" content=" 专题1：Exception &middot;  Advanced C&#43;&#43; Seminar Notebook" />
  
  <meta name="theme-color" content="#66CCFF" />
 
  <meta property="og:site_name" content="Advanced C&#43;&#43; Seminar Notebook" />
  <meta property="og:url" content="https://acppsn.netlify.app/post/exception/" />
  
  
  <meta property="og:type" content="article" />
  
  <meta property="og:article:published_time" content="2021-03-13T11:56:19&#43;08:00" />
  
  

  <title>
     专题1：Exception &middot;  Advanced C&#43;&#43; Seminar Notebook
  </title>

  <link rel="stylesheet" href="https://acppsn.netlify.app/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://acppsn.netlify.app/css/main.css" />
  <link rel="stylesheet" href="https://acppsn.netlify.app/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://acppsn.netlify.app/css/github.css" />
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400" type="text/css">
  <link rel="shortcut icon" href="https://acppsn.netlify.app/images/favicon.ico" />
  <link rel="apple-touch-icon" href="https://acppsn.netlify.app/images/apple-touch-icon.png" />
  
</head>
<body>
    <header class="global-header"  style="background-image:url( /images/bg.jpg )">
    <section class="header-text">
      <h1><a href="https://acppsn.netlify.app/">Advanced C&#43;&#43; Seminar Notebook</a></h1>
      
      <div class="tag-line">
        当你拿着C&#43;&#43;这把锤子，看什么都像钉子
      </div>
      
      <div class="sns-links hidden-print">
  
  
  
  
  
  
  <a href="https://github.com/NeilKleistGao" target="_blank">
    <i class="fa fa-github"></i>
  </a>
  
  
  
  
  
  
  
</div>

      
      <a href="https://acppsn.netlify.app/" class="btn-header btn-back hidden-xs">
        <i class="fa fa-angle-left" aria-hidden="true"></i>
        &nbsp;Home
      </a>
      
      
    </section>
  </header>
  <main class="container">


<article>
  <header>
    <h1 class="text-primary">专题1：Exception</h1>
    <div class="post-meta clearfix">
    
      <div class="post-date pull-left">
        Posted on
        <time datetime="2021-03-13T11:56:19&#43;08:00">
          Mar 13, 2021
        </time>
      </div>
    
      <div class="pull-right">
        
      </div>
    </div>
  </header>
  <section>
    <h2 id="前言">前言</h2>
<hr>
<h2 id="c-exception实现机制">C++ Exception实现机制</h2>
<p>作者：<a href="https://github.com/NeilKleistGao">NeilKleistGao</a></p>
<hr>
<h3 id="环境申明">环境申明</h3>
<ul>
<li>操作系统: Windows10</li>
<li>IDE: Visual Studio 2019</li>
<li>编译器：MSVC 19</li>
<li>C++标准：C++17</li>
<li>优化选项：无优化</li>
</ul>
<h3 id="stdexception实现">std::exception实现</h3>
<p>MSVC下<code>std::exception</code>的实现在头文件<code>vcruntime_exception.h</code>中：</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">exception</span>
{
<span style="color:#66d9ef">public</span><span style="color:#f92672">:</span>
    exception() <span style="color:#66d9ef">noexcept</span>
        <span style="color:#f92672">:</span> _Data()
    {
    }

    <span style="color:#66d9ef">explicit</span> <span style="color:#a6e22e">exception</span>(<span style="color:#66d9ef">char</span> <span style="color:#66d9ef">const</span><span style="color:#f92672">*</span> <span style="color:#66d9ef">const</span> _Message) <span style="color:#66d9ef">noexcept</span>
        <span style="color:#f92672">:</span> _Data()
    {
        __std_exception_data _InitData <span style="color:#f92672">=</span> { _Message, true };
        __std_exception_copy(<span style="color:#f92672">&amp;</span>_InitData, <span style="color:#f92672">&amp;</span>_Data);
    }

    exception(<span style="color:#66d9ef">char</span> <span style="color:#66d9ef">const</span><span style="color:#f92672">*</span> <span style="color:#66d9ef">const</span> _Message, <span style="color:#66d9ef">int</span>) <span style="color:#66d9ef">noexcept</span>
        <span style="color:#f92672">:</span> _Data()
    {
        _Data._What <span style="color:#f92672">=</span> _Message;
    }

    exception(exception <span style="color:#66d9ef">const</span><span style="color:#f92672">&amp;</span> _Other) <span style="color:#66d9ef">noexcept</span>
        <span style="color:#f92672">:</span> _Data()
    {
        __std_exception_copy(<span style="color:#f92672">&amp;</span>_Other._Data, <span style="color:#f92672">&amp;</span>_Data);
    }

    exception<span style="color:#f92672">&amp;</span> <span style="color:#66d9ef">operator</span><span style="color:#f92672">=</span>(exception <span style="color:#66d9ef">const</span><span style="color:#f92672">&amp;</span> _Other) <span style="color:#66d9ef">noexcept</span>
    {
        <span style="color:#66d9ef">if</span> (<span style="color:#66d9ef">this</span> <span style="color:#f92672">==</span> <span style="color:#f92672">&amp;</span>_Other)
        {
            <span style="color:#66d9ef">return</span> <span style="color:#f92672">*</span><span style="color:#66d9ef">this</span>;
        }

        __std_exception_destroy(<span style="color:#f92672">&amp;</span>_Data);
        __std_exception_copy(<span style="color:#f92672">&amp;</span>_Other._Data, <span style="color:#f92672">&amp;</span>_Data);
        <span style="color:#66d9ef">return</span> <span style="color:#f92672">*</span><span style="color:#66d9ef">this</span>;
    }

    <span style="color:#66d9ef">virtual</span> <span style="color:#f92672">~</span>exception() <span style="color:#66d9ef">noexcept</span>
    {
        __std_exception_destroy(<span style="color:#f92672">&amp;</span>_Data);
    }

    _NODISCARD <span style="color:#66d9ef">virtual</span> <span style="color:#66d9ef">char</span> <span style="color:#66d9ef">const</span><span style="color:#f92672">*</span> <span style="color:#a6e22e">what</span>() <span style="color:#66d9ef">const</span>
    {
        <span style="color:#66d9ef">return</span> _Data._What <span style="color:#f92672">?</span> _Data._What : <span style="color:#e6db74">&#34;Unknown exception&#34;</span>;
    }

<span style="color:#66d9ef">private</span><span style="color:#f92672">:</span>

    __std_exception_data _Data;
};
</code></pre></div><p>其中<code>__std_exception_data</code>为一个结构体，包含一个what字符串和一个清理标志。</p>
<p>Linux下的实现和该实现类似，但不包含有<code>char const* const message</code>参数的构造函数。</p>
<h3 id="__cxxthrowexception">__CxxThrowException</h3>
<p>我们以一个简单的<code>try/catch</code>为例：</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;iostream&gt;</span><span style="color:#75715e">
</span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;exception&gt;</span><span style="color:#75715e">
</span><span style="color:#75715e"></span>
<span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span>() {
	<span style="color:#66d9ef">try</span> {
		<span style="color:#66d9ef">throw</span> std<span style="color:#f92672">::</span>exception(<span style="color:#e6db74">&#34;test&#34;</span>);
	}
	<span style="color:#66d9ef">catch</span> (<span style="color:#66d9ef">const</span> std<span style="color:#f92672">::</span>exception<span style="color:#f92672">&amp;</span> e) {
		std<span style="color:#f92672">::</span>cout <span style="color:#f92672">&lt;&lt;</span> e.what() <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
	}

	<span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
}
</code></pre></div><p>根据上一节的内容，我们在<code>std::exception</code>类内部找不到异常处理的内容：它只是一个存储异常信息数据的类，而不负责异常处理逻辑。</p>
<p>我们使用反汇编查看对应的汇编代码：</p>
<pre><code class="language-assembly" data-lang="assembly">mov         dword ptr [ebp-4],0
push        offset string &quot;test&quot;
lea         ecx,[ebp-0F8h]
call        std::exception::exception
push        offset __TI1?AVexception@std@@
lea         eax,[ebp-0F8h]
push        eax
call        __CxxThrowException@8
</code></pre><p>可以看到<code>try</code>部分内的逻辑，本质上是调用了一个<code>__CxxThrowException</code>函数来进行处理的，这个函数应该有两个参数（两次<code>push</code>）。</p>
<p>我们可以在微软官方的文档中找到这个函数的声明：</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#66d9ef">extern</span> <span style="color:#e6db74">&#34;C&#34;</span> <span style="color:#66d9ef">void</span> <span style="color:#66d9ef">__stdcall</span> _CxxThrowException(
   <span style="color:#66d9ef">void</span><span style="color:#f92672">*</span> pExceptionObject,
   _ThrowInfo<span style="color:#f92672">*</span> pThrowInfo
);
</code></pre></div><p>其中第一个参数是产生异常的对象，第二个参数是处理异常所需要的信息。由于该函数使用<code>__srdcall</code>修饰，<code> __TI1?AVexception@std@@</code>对应<code>_ThrowInfo</code>类型指针。</p>
<p><strong>不要直接调用该函数，该函数应该交由编译器处理。</strong></p>
<p>这个函数真正意义上“抛出了一个异常”。该函数将会创建一个异常记录（exception record），并要求运行时环境处理该异常。如果程序顺利执行完毕没有触发异常，一个<code>jmp</code>指令将会被用于跳过<code>catch</code>部分。</p>
<p>由于<code>__CxxThrowException</code>无法查阅到其实现方式，只能看到反汇编的结果，难以阅读，我们尝试通过使用IDA来定位<code>catch</code>语句被引用的地方：</p>
<p><img src="https://i.loli.net/2021/03/25/mFoSN5fU6g7Kiza.png" alt=""></p>
<p>我们可以看到编译器保存了函数的相关信息（FuncInfo）结构体：其中包含了两个回退（Unwind）结构体（下文中会再提到），以及一个HandlerType，该结构体中保存有catch对应的偏移地址以及<code>exception</code>的虚表指针（<code>stru_41C138</code>中，在<code>_ThrowInfo</code>也包含有指向该结构体的指针）。</p>
<p>FuncInfo的定义如下（已删除宏和注释，完整见<code>ehdata.h</code>）：</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#66d9ef">typedef</span> <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">struct</span> <span style="color:#a6e22e">_s_FuncInfo</span>
{
	<span style="color:#66d9ef">unsigned</span> <span style="color:#66d9ef">int</span>		magicNumber:<span style="color:#ae81ff">29</span>;		
	<span style="color:#66d9ef">unsigned</span> <span style="color:#66d9ef">int</span>		bbtFlags:<span style="color:#ae81ff">3</span>;			
	__ehstate_t			maxState;			
	UnwindMapEntry<span style="color:#f92672">*</span>		pUnwindMap; <span style="color:#75715e">// 回退表
</span><span style="color:#75715e"></span>	<span style="color:#66d9ef">unsigned</span> <span style="color:#66d9ef">int</span>		nTryBlocks;
	TryBlockMapEntry<span style="color:#f92672">*</span>	pTryBlockMap; <span style="color:#75715e">// try块表
</span><span style="color:#75715e"></span>	<span style="color:#66d9ef">unsigned</span> <span style="color:#66d9ef">int</span>		nIPMapEntries;
	<span style="color:#66d9ef">void</span><span style="color:#f92672">*</span>				pIPtoStateMap;
	ESTypeList<span style="color:#f92672">*</span>			pESTypeList;
	<span style="color:#66d9ef">int</span>					EHFlags;
} FuncInfo;
</code></pre></div><p>我们跳过<code>TryBlockMapEntry</code>（同样在<code>ehdata.h</code>中），直接来看<code>HandlerType</code>：</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#66d9ef">typedef</span> <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">struct</span> <span style="color:#a6e22e">_s_HandlerType</span> {
	<span style="color:#66d9ef">unsigned</span> <span style="color:#66d9ef">int</span>	adjectives;
	TypeDescriptor<span style="color:#f92672">*</span>	pType; <span style="color:#75715e">// 类型描述符，根据之前逆向的结果，其中包含有虚表指针
</span><span style="color:#75715e"></span>	ptrdiff_t		dispCatchObj;
	<span style="color:#66d9ef">void</span> <span style="color:#f92672">*</span>			addressOfHandler; <span style="color:#75715e">// catch地址
</span><span style="color:#75715e"></span>} HandlerType;
</code></pre></div><p><code>__CxxThrowException</code>首先会检索<code>FuncInfo</code>，找到对应的try entry，并根据try entry 结构后附带的catch entry逐一匹配，找到合适的处理代码。如果无法找到，则需要涉及到栈回退。</p>
<h3 id="stack-unwind栈回退">Stack Unwind（栈回退）</h3>
<p>如果<code>exception</code>无法被捕获，运行时环境需要跳转到更高一层的上下文（higher execution context）中寻找<code>catch</code>块；如果程序完全没有理会该<code>exception</code>，则程序将会调用<code>terminate</code>函数自动终止。</p>
<p>关键问题就在于：我们要如何完成“跳转”操作？考虑下面的这段代码：</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;iostream&gt;</span><span style="color:#75715e">
</span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;exception&gt;</span><span style="color:#75715e">
</span><span style="color:#75715e"></span>
<span style="color:#66d9ef">struct</span> <span style="color:#a6e22e">Foo</span>
{
	<span style="color:#f92672">~</span>Foo() {
		std<span style="color:#f92672">::</span>cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;rua&#34;</span> <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
	}
};

<span style="color:#66d9ef">void</span> <span style="color:#a6e22e">foo</span>() {
	Foo f;
	<span style="color:#66d9ef">throw</span> std<span style="color:#f92672">::</span>exception(<span style="color:#e6db74">&#34;test&#34;</span>);
}

<span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span>() {
	
	<span style="color:#66d9ef">try</span> {
		foo();
	}
	<span style="color:#66d9ef">catch</span> (std<span style="color:#f92672">::</span>exception e) {
		<span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>	}
	
	<span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
}
</code></pre></div><p>我们在<code>foo</code>函数中抛出一个异常，我们该如何在<code>main</code>中将其捕获？</p>
<p>接着上一节的内容，我们来查看回退相关的结构体：</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#66d9ef">typedef</span> <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">struct</span> <span style="color:#a6e22e">_s_UnwindMapEntry</span> {
	__ehstate_t	toState;
	<span style="color:#66d9ef">void</span>		(<span style="color:#66d9ef">__cdecl</span> <span style="color:#f92672">*</span> action)(<span style="color:#66d9ef">void</span>);
} UnwindMapEntry;
</code></pre></div><p>该结构体中包含有一个<code>funclet</code>，当异常被抛出而找不到<code>catch</code>时，程序会自动调用该<code>funclet</code>，它将完成栈回退的计算，以及必要的析构操作等。如果<code>toState</code>值为<code>-1</code>，则代表当前函数处在最上层。</p>
<p>我们可以使用IDA查看<code>foo</code>函数的回退<code>funclet</code>：</p>
<p><img src="https://i.loli.net/2021/03/25/krmiUqD4boXZjEK.png" alt=""></p>
<p>可以看到其的确调用了<code>Foo</code>结构体的析构函数。由于<code>foo</code>函数没有参数，所以不需要进行额外的调整。</p>
<hr>
<h2 id="异常默认处理情况">异常默认处理情况</h2>
<p>作者：<a href="https://github.com/gerayking">gerayking</a></p>
<hr>
<p>当发生异常当未有异常捕捉进行处理时，在默认情况下，这将导致程序异常终止，这种情况成为<strong>意外异常</strong>，</p>
<p>这种情况下，程序将会调用terminate()，默认情况下，terminate()会调用abort()函数。</p>
<p>而在大多数情况下，项目如果因为出现异常而宕机是很危险的行为，所以可以直接修改terminate()函数进行意外异常的根本处理.</p>
<pre><code>Function handling termination on exception
Calls the current terminate handler.

By default, the terminate handler calls abort. But this behavior can be redefined by calling set_terminate.

This function is automatically called when no catch handler can be found for a thrown exception, or for some other exceptional circumstance that makes impossible to continue the exception handling process.

This function is provided so that the terminate handler can be explicitly called by a program that needs to abnormally terminate, and works even if set_terminate has not been used to set a custom terminate handler (calling abort in this case).


</code></pre><p>cite  <a href="http://www.cplusplus.com/reference/exception/terminate/">C++ reference</a></p>
<p>C++提供了<code>set_terminate</code>的方法交给程序员来自定义兜底的函数处理。</p>
<p>具体使用实例如下</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-cpp" data-lang="cpp"><span style="color:#75715e">// terminate example
</span><span style="color:#75715e"></span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;iostream&gt;       // std::cout, std::cerr</span><span style="color:#75715e">
</span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;exception&gt;      // std::exception, std::terminate</span><span style="color:#75715e">
</span><span style="color:#75715e"></span><span style="color:#66d9ef">using</span> <span style="color:#66d9ef">namespace</span> std;
<span style="color:#66d9ef">void</span> <span style="color:#a6e22e">MyQuit</span>(){
    cout<span style="color:#f92672">&lt;&lt;</span><span style="color:#e6db74">&#34;Terminate due to uncaught exception !!!!</span><span style="color:#ae81ff">\n</span><span style="color:#e6db74">&#34;</span>;
    exit(<span style="color:#ae81ff">5</span>);
}
<span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span> (<span style="color:#66d9ef">void</span>) {
    set_terminate(MyQuit);
    <span style="color:#66d9ef">try</span> {
        <span style="color:#66d9ef">throw</span> <span style="color:#e6db74">&#34;as&#34;</span>;
    }
    <span style="color:#66d9ef">catch</span> (exception <span style="color:#f92672">&amp;</span>a) {
        std<span style="color:#f92672">::</span>cout<span style="color:#f92672">&lt;&lt;</span><span style="color:#e6db74">&#34;caught exception !!!</span><span style="color:#ae81ff">\n</span><span style="color:#e6db74">&#34;</span>;
    }
    <span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
}
</code></pre></div><hr>
<h2 id="通过值抛出通过引用捕获">通过值抛出，通过引用捕获</h2>
<p>作者：<a href="https://github.com/PtCu">PtCu</a></p>
<hr>
<p>—— Excerpt from 《 C++ Coding Standards: 101 Rules,  guidelines and best practices 》</p>
<p><strong>摘要</strong></p>
<p>​	学习正确捕获 (catch)：按值（而不是指针）抛出异常，并按引用（通常为const的引用）捕获异常，这是与异常语义配合最佳的组合。当抛出相同的异常时，应该优先使用throw;, 避免使用throw e;</p>
<p><strong>讨论</strong></p>
<p>​	抛出异常时，要通过值抛出对象，避免抛出指针，因为如果抛出指针，则需要处理内存管理问题。不能抛出指向堆栈分配值的指针，因为在指针到达调用处之前栈还没有展开。虽然抛出指向动态分配内存的指针是可行的 [如果要报告的错误不是以 &ldquo;out of memory&rdquo; (内存不足）开始的], 但是这样就将释放内存的负担放在了捕获处。如果确实必须抛出一个指针，请考虑抛出诸如shared_ptr &lt;T&gt; 之类的类似于值的智能指针，而不是普通的T *。
​	通过值抛出可以说是 “集人间宠爱于一身”，因为这时编译器本身将负责管理异常对象的内存这一负责过程。我们所需要操心的就是确保为异常类实现一个非抛出的副本构造函数。
​	除非要抛出的是智能指针（这已经增加了要保持多态的间接性），否则通过引用捕获异常就是唯一可行的好办法。按值捕获纯值会导致在捕获处引起切片问题，这会粗暴地去除通常至关重要的异常对象的多态性。通过引用捕获可以保留异常对象的多态性。
在重新抛出异常e时，应该只写成throw；而不是throw e;，因为第一种形式总是能够保持重新抛出对象的多态性。</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-cpp" data-lang="cpp"><span style="color:#66d9ef">catch</span>( MyException<span style="color:#f92672">&amp;</span> e ) { <span style="color:#75715e">//catch by reference to
</span><span style="color:#75715e"></span>    non<span style="color:#f92672">-</span>conste.AppendContext(<span style="color:#e6db74">&#34;Passed through here&#34;</span>);   <span style="color:#75715e">//modify
</span><span style="color:#75715e"></span>    <span style="color:#66d9ef">throw</span>;
    }
</code></pre></div><hr>
<h2 id="内存管理">内存管理</h2>
<p>作者：<a href="https://github.com/buggyminer">buggyminer</a></p>
<hr>
<p>异常的存在破坏了函数的封闭性。在有关内存操作的函数中产生的异常很容易产生内存问题。
比如，构造函数执行不完全时产生了异常，会导致对象只构造了一部分，且这部分占用的内存不会被析构函数释放。当然，在构造函数中抛出异常是推荐的做法，由异常信息代替了错误码——因为构造函数不能有返回值。否则，就不得不为所有可能构造失败的对象创建一个zombie状态，并编写一个特定的检活成员函数，还需要在所有可能的地方加入额外的判断条件——对象是否为zombie。
同样地，析构函数执行时产生了异常，可能导致内存泄漏问题。
对于构造函数，大致有以下解决思路：</p>
<p>1、使用智能指针</p>
<p>这是推荐的做法。
将需要动态申请的资源分配到智能指针上，那么可以保证当程序退出构造函数时，智能指针被销毁，其指向的内存得到释放。</p>
<p>2、用try-catch块单独包裹构造函数</p>
<p>不推荐。除非该对象是一个单例类，否则都会违背DRY原则。</p>
<p>3、在构造函数内部捕获异常并再次抛出</p>
<p>在内部的异常处理中，仅仅进行资源的释放。如果有必要，可以附加更多的异常信息。</p>
<p>4、在构造函数内部捕获异常并不抛出</p>
<p>对于有些类，即使创建失败，对象并没有占有任何资源时，其仍然可以视为一个自洽的系统。比如stack，我们需要不断地判断其是否为空。面对这种情况，在构造函数内部处理异常并使对象迁移到一个合法的“空”状态是完全可行的。</p>
<p>5、使用两段构造函数</p>
<p>破除了构造函数没有返回值的窘境，在语义上将构造拆分成了更小的单元，是完全可行的。虽然有些人认为没有必要或不够优雅，我可不觉得。</p>
<p>而对于析构函数，问题就简单的多：</p>
<blockquote>
<p>You can throw an exception in a destructor, but that exception must not leave the destructor; if a destructor exits by emitting an exception, all kinds of bad things are likely to happen because the basic rules of the standard library and the language itself will be violated. Don’t do it. <em>isocpp</em></p>
</blockquote>
<blockquote>
<p>Item 11: Prevent exceptions from leaving destructors <em>more effective C++</em></p>
</blockquote>
<p>析构函数的异常必须在析构函数中捕捉。
如果抛出异常，就说明内存泄漏已经发生，析构函数未能完成它的工作。
此外，如果析构函数是在处理异常的代码中被调用，那么析构函数产生的异常会直接触发terminate。而我们知道，析构函数作为资源释放的函数经常用于处理异常，因此它自身必须是严格异常安全的。为了提高性能，可以加上nonexcept；这样还有一个好处，就是能够尽早地让有问题的析构函数崩溃，从而暴露问题。</p>
<p>src：</p>
<p><a href="https://isocpp.org/files/papers/P1676R0.pdf">C++ Exception Optimizations. An experiment.</a></p>
<p><a href="https://isocpp.org/wiki/faq/exceptions">Exceptions and Error Handling</a></p>
<p><a href="https://www.iso.org/standard/68564.html">C++17 standard</a></p>
<hr>
<h2 id="catch-by-value--determinism">catch by value &amp; determinism</h2>
<p>作者：<a href="https://github.com/buggyminer">buggyminer</a></p>
<hr>
<p>主要来自Herb Sutter的两篇论文。他主张使用静态的异常类型检查以及按值捕获，希望通过这一方式在保证C++语言的统一性的同时消弭两种错误处理方式的分歧——异常和错误码。</p>
<blockquote>
<p>This paper aims to extend C++’s exception model to let functions declare that they throw a statically specified  type by value. This lets the exception handling implementation be exactly as efficient and deterministic as a local return by value, with zero dynamic or non-local overheads.</p>
</blockquote>
<blockquote>
<p>Importantly, “zero overhead” is not claiming zero cost — of course using something always incurs  some cost. Rather, C++’s zero-overhead principle has always meant that (a) “you don’t pay for what  you don’t use” and (b) “when you do use it you can’t [reasonably] write it more efficiently by hand.”</p>
</blockquote>
<p>exception的使用会对C++程序产生诸多性能上的影响，如二进制图像膨胀、运行时开销等问题，还会使得程序失去其时间和空间开销的确定性——后者对实时性高的系统而言是不能接收的。这些现象的根本原因是异常的存在违背了C++的两个基本原则，即零开销原则和确定性原则。</p>
<blockquote>
<p>The <strong>zero-overhead principle</strong> is a C++ design principle that states:</p>
<ol>
<li>You don&rsquo;t pay for what you don&rsquo;t use.</li>
<li>What you do use is just as efficient as what you could reasonably write by hand.</li>
</ol>
</blockquote>
<blockquote>
<p><strong>Determinism</strong>, in philosophy, theory that all events, including moral choices, are completely determined by previously existing causes. Determinism is usually understood to preclude free will because it entails that humans cannot act otherwise than they do.</p>
</blockquote>
<p>异常需要根据其动态类型进行处理，这就引出了一个经典的问题：dynamic_cast的复杂度是多少？</p>
<p>总之，exception在C++中的实现导致了其运行期的不确定性，并在一些情况下大幅提高了程序的开销，并需要RTTI的配合。具体解释请阅读原论文。</p>
<p>程序员喜欢折中。以下是作者给出的折中解决方案。</p>
<p><img src="https://i.loli.net/2021/03/28/5KC6dkSyV3JBMO7.png" alt="image-20210328155735397"></p>
<p><img src="https://i.loli.net/2021/03/28/3TWglRbFHEL2rOa.png" alt="image-20210328161655752"></p>
<p>异常是动态的。但是我们可以使用静态的异常，从而在编译期就得以确认程序的开销和性能。为了节省空间和保证一致性，往往通过引用捕捉异常——需要不断地在栈中获取异常的地址。但是在使用静态异常的前提下，我们就可以按值捕捉异常，避免了寻址的开销并保证了其唯一性。</p>
<p>即，使用异常的处理方式来传递错误码。</p>
<p>此外，他在新的论文中提出了一种完全消除全新的层次异常处理方式，可以完全取出任何按引用捕获异常的必要性。当然，现在还不能用。</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-c++" data-lang="c++"><span style="color:#66d9ef">try</span>
{
	f(); <span style="color:#75715e">// Calls open_file internally
</span><span style="color:#75715e"></span>}
<span style="color:#66d9ef">catch</span>( file_error, open_error, file_name fn )
{
	<span style="color:#75715e">// Handle a &#34;file error&#34; that is also an &#34;open error&#34; and has an associated file name.
</span><span style="color:#75715e"></span>	std<span style="color:#f92672">::</span>cerr <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;Failed to open file &#34;</span> <span style="color:#f92672">&lt;&lt;</span> fn.value <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
}
<span style="color:#66d9ef">catch</span>( file_error, file_name fn )
{
	<span style="color:#75715e">// Handle any &#34;file error&#34; that has an associated file name.
</span><span style="color:#75715e"></span>	std<span style="color:#f92672">::</span>cerr <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;Failed to to access file &#34;</span> <span style="color:#f92672">&lt;&lt;</span> fn.value <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
}
<span style="color:#66d9ef">catch</span>( file_error )
{
	<span style="color:#75715e">// Handle any &#34;file error&#34;.
</span><span style="color:#75715e"></span>	std<span style="color:#f92672">::</span>cerr <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;Failed to access file&#34;</span> <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
}
</code></pre></div><p>src：</p>
<p>[Zero-Overhead Deterministic Exceptions: Catching Values](<a href="http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2021/p2232r0.html">Zero-Overhead Deterministic Exceptions: Catching Values (open-std.org)</a>)</p>
<p>[Zero-overhead deterministic exceptions: Throwing values](<a href="http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2018/p0709r0.pdf">p0709r0.pdf (open-std.org)</a>)</p>
<hr>

  </section>
  <footer>
    
    
    
    <section class="author-info row">
      <div class="author-avatar col-md-2">
        
        <img alt="Author Avatar" src="/avatar.jpg" />
        
      </div>
      <div class="author-meta col-md-6">
        
        <h1 class="author-name text-primary">Advanced C&#43;&#43; Seminar</h1>
        
        
        <div class="author-bio">XD</div>
        
      </div>
      
    </section>
    <ul class="pager">
      
      <li class="previous"><a href="https://acppsn.netlify.app/about/"><span aria-hidden="true">&larr;</span>Older</a></li>
      
      
      <li class="next disabled"><a href="#">Newer<span aria-hidden="true">&rarr;</span></a></li>
      
    </ul>
  </footer>
</article>

  </main>
  <footer class="container global-footer">
    <div class="copyright-note pull-left">
      &copy; CC0-1.0 License
    </div>
    <div class="sns-links hidden-print">
  
  
  
  
  
  
  <a href="https://github.com/NeilKleistGao" target="_blank">
    <i class="fa fa-github"></i>
  </a>
  
  
  
  
  
  
  
</div>

  </footer>

  <script src="https://acppsn.netlify.app/js/highlight.pack.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
  
  
</body>
</html>

